# Set the following variables before running:
@oktaDomain = integrator-7620286.okta.com
@oktaClientId = 0oazoxkr5qr5bSJFs697
@subscriptionId = 3019d4d5-a172-4635-877f-9ad4001cfa85
@resourceGroupName = karansin
@botName = teams-okta-oauth-bot
@connectionName = okta

# Get access token with: az account get-access-token --query accessToken -o tsv
@accessToken = YOUR_ACCESS_TOKEN_HERE

### Create or Update OAuth Connection on Azure Bot Service
# This configures the Generic OAuth 2 provider with Okta endpoints
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.BotService/botServices/{{botName}}/connections/{{connectionName}}?api-version=2022-09-15
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "location": "global",
  "properties": {
    "serviceProviderId": "8379c6d2-b262-4d4f-b89b-68dc5b5f5482",
    "serviceProviderDisplayName": "Oauth 2 Generic Provider",
    "clientId": "{{oktaClientId}}",
    "clientSecret": "YOUR_OKTA_CLIENT_SECRET",
    "scopes": "openid profile email",
    "parameters": [
      {
        "key": "authorizationUrl",
        "value": "https://{{oktaDomain}}/oauth2/default/v1/authorize"
      },
      {
        "key": "tokenUrl",
        "value": "https://{{oktaDomain}}/oauth2/default/v1/token"
      },
      {
        "key": "refreshUrl",
        "value": "https://{{oktaDomain}}/oauth2/default/v1/token"
      },
      {
        "key": "clientId",
        "value": "{{oktaClientId}}"
      },
      {
        "key": "clientSecret",
        "value": "YOUR_OKTA_CLIENT_SECRET"
      },
      {
        "key": "scopes",
        "value": "openid profile email"
      },
      {
        "key": "authorizationUrlTemplate",
        "value": "https://{{oktaDomain}}/oauth2/default/v1/authorize"
      },
      {
        "key": "tokenUrlTemplate",
        "value": "https://{{oktaDomain}}/oauth2/default/v1/token"
      },
      {
        "key": "refreshUrlTemplate",
        "value": "https://{{oktaDomain}}/oauth2/default/v1/token"
      }
    ]
  }
}

###

### Get OAuth Connection Configuration (verify)
GET https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.BotService/botServices/{{botName}}/connections/{{connectionName}}?api-version=2022-09-15
Authorization: Bearer {{accessToken}}

###

### Test OAuth Connection
POST https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.BotService/botServices/{{botName}}/connections/{{connectionName}}/listWithSecrets?api-version=2022-09-15
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}
